// Getters
export const PEMINJAM = "PEMINJAM";
export const PEMINJAMANDATA = "PEMINJAMANDATA";
export const IMAGE_PEMINJAM = "IMAGE_PEMINJAM";

// Mutations
export const MUTATE_PEMINJAM = "MUTATE_PEMINJAM";
export const MUTATE_PEMINJAMANDATA = "MUTATE_PEMINJAMANDATA";
export const MUTATE_IMAGE_PEMINJAM = "MUTATE_IMAGE_PEMINJAM";

// Actions
export const UPDATE_PEMINJAM = "UPDATE_PEMINJAM";
export const UPDATE_PEMINJAMANDATA = "UPDATE_PEMINJAMANDATA";
export const UPDATE_IMAGE_PEMINJAM = "UPDATE_IMAGE_PEMINJAM";
